/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as FeedbackIdRouteImport } from './routes/feedback/$id'
import { Route as SessionIdRouteImport } from './routes/session/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIdRoute = FeedbackIdRouteImport.update({
  id: '/feedback/$id',
  path: '/feedback/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/feedback/$id': typeof FeedbackIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/onboarding'
    | '/plan'
    | '/feedback/$id'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/onboarding'
    | '/plan'
    | '/feedback/$id'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/onboarding'
    | '/plan'
    | '/feedback/$id'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  FeedbackIdRoute: typeof FeedbackIdRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$id': {
      id: '/feedback/$id'
      path: '/feedback/$id'
      fullPath: '/feedback/$id'
      preLoaderRoute: typeof FeedbackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  FeedbackIdRoute: FeedbackIdRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
